### ISSUE TITLE
Options Filter/Function

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Simple-Page-Builder#12]
As we discussed on Skype, would be super cool if there was an options filter. Much like how we use [wp_nav_menu](http://codex.wordpress.org/Function_Reference/wp_nav_menu#Usage)

``` php
wds_client_page_builder_options( array(
   'container'       => 'section',
   'container_class' => 'part-container',
   'parts_folder'    => 'parts',
   etc...
) );
```

**Comment by jazzsequence** [comment]
If this is a sort of initial setup-type function, I'm thinking it would work similar to [`register_page_builder_layout`](https://github.com/WebDevStudios/WDS-Simple-Page-Builder/wiki/Registering-Layouts#register_page_builder_layout-layout_name-parts_array-user_editable-), i.e.:

``` php
wds_register_page_builder_options( array(
     'parts_dir' => 'parts',
     'parts_prefix' => 'part',
     'container' => 'section',
     'container_class' => 'part-container',
     'global_layout' => array(),
     'hide_options' => true
) );
```

I also think having some way to hide or disable options that you're registering this way would be necessary (the `hide_options` parameter above) -- otherwise you have the possibility of registering these options but you have a page where they are visible and editable to the user...so either the user edits them, and they are always changed back to how you registered them, or you allow them to edit the settings, and they potentially break everything.

**Comment by jazzsequence** [comment]
added in 1bf82fb815214609f7eb4311733b8bf80137db46

also added support for `add_theme_support`
