### ISSUE TITLE
Color picker and radio (inline) losing values when changing template position

### ISSUE THREAD

**Issue by efuller** [WebDevStudios/WDS-Simple-Page-Builder#42]
The 2 fields field types in question are the color picker and the radio (inline).

When changing the order of templates, the fields are not keeping their values.

(gif)
![pagebuilderissue-fieldsnotsavingonmove](https://cloud.githubusercontent.com/assets/4174472/10111521/9c997ddc-63a2-11e5-9b28-70f836952474.gif)

**Comment by jazzsequence** [comment]
@jtsternberg ping ^^

**Comment by jazzsequence** [comment]
to add more detail, it's not all fields that lose their values. in the example above, it's just the color picker and the radio buttons.

**Comment by JayWood** [comment]
I'm in the process of merging refactor-2 into develop.  Once that's done I'll debug this for you.  I had a look at the JS last week and this seems purely JS related ( obviously ) but I think I know what to do.

**Comment by JayWood** [comment]
We found the issue with the color picker, that was actually an issue with CMB2 and was fixed in WebDevStudios/CMB2@e32d87f17d726e197aefd865d86cce6beee4dfd9 thanks to @jtsternberg I was close though!

Also, queuing up the latest version of CMB2 seems to have fixed the radio issue, which I'll test further.
