### ISSUE TITLE
Group Fields

### ISSUE THREAD

**Issue by stompweb** [WebDevStudios/WDS-Simple-Page-Builder#63]
I've setup a custom field for one of the templates like so:

```
function wds_add_custom_feature_fields( $fields ) {
    $new_fields = array(
        array(
                'name'    => esc_html__( 'Custom Title', 'textdomain' ),
                'id'      => 'wds_custom_title',
                'type'    => 'text_medium',
            ),
            array(
                'name'    => esc_html__( 'Custom Content', 'textdomain' ),
                'id'      => 'wds_custom_content',
                'type'    => 'wysiwyg',
                'options' => array( 'textarea_rows' => 5, ),
            ),
    );
    return array_merge( $fields, $new_fields );
}
add_filter( 'wds_page_builder_fields_test', 'wds_add_custom_feature_fields' );
```

I took that from the documentation so it was quite simple, however I'm having issues creating a group field as the data is a little different from CMB2.

Is this something that could be added to the Wiki please?

**Comment by jazzsequence** [comment]
Hi @stompweb 
I have a feeling your question might have already been answered in the CMB2 issue tracker (? maybe?) but I'll answer it here anyway...

If I'm understanding your implementation correctly, you can't group fields in a page builder metabox because it's already a group and you can't nest groups. Let me know if I'm misunderstanding your question.

**Comment by stompweb** [comment]
It was answered on Twitter, @jazzsequence thanks for following up.
